### ISSUE TITLE
Issues when compiling

### ISSUE THREAD

**Issue by tanderson9** [textiles-lab/knitout-frontend-py#1]
Getting the following when trying to run the examples:

import-im6.q16: not authorized `re' @ error/constitute.c/WriteImage/1037.
./knitout.py: line 5: validHeaders: command not found
./knitout.py: line 9: syntax error near unexpected token `('
./knitout.py: line 9: `reg = re.compile("([a-zA-Z]+)([\+\-]?[0-9]+)")'

**Comment by vid8687** [comment]
I added the python3 env shebang to the start of the file -- that should fix this. Can you test with the most recent version ?

**Comment by tanderson9** [comment]
I can confirm it compiles now. Thanks.
